### ISSUE TITLE
Comment here to be invited to join the codeforokc github group

### ISSUE THREAD

**Issue by jagthedrummer** [codeforokc/discussions#5]

**Comment by Mike-Loffland** [comment]
Hilo

**Comment by sivins** [comment]
Halito!

**Comment by darrenjaworski** [comment]
yo, add me to your group

**Comment by okjed** [comment]
Commenting as well

**Comment by Arrowlyn31** [comment]
Hello!

**Comment by jagthedrummer** [comment]
Hey there, @Arrowlyn31, looks like you're already a member of the group, so you won't see an invitation coming your way. Everyone else that has commented here should have already received an invitation.

**Comment by tcdobbs** [comment]
Good morning, hope I'm not too late.

**Comment by mkchandler** [comment]
@tcdobbs Nope! You should see an invite coming your way.

**Comment by courtlam** [comment]
Hi

**Comment by linuxuser07** [comment]
Can I still join?

**Comment by mkchandler** [comment]
@linuxuser07 It's never too late! You should see an invite coming your way.

**Comment by linuxuser07** [comment]
Thank you @mkchandler

**Comment by porterchris** [comment]
o7
